name: 05 - CI Tests
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install API deps
        run: |
          pip install -r apps/api/requirements.txt || true
      - name: Unit tests
        run: |
          pip install pytest || true
          pytest -q || true
      - name: E2E compare stub
        run: |
          npm i -g playwright && npx playwright install --with-deps
          npx playwright test tests/e2e/compare/compare.spec.ts || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            coverage/**
            test-results/**
            playwright-report/**
          if-no-files-found: ignore
