name: 06 - Bug Report
on:
  workflow_run:
    workflows: ["05 - CI Tests"]
    types: [ completed ]
jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Summarize failures to docs/09_bug_report.md
        run: |
          echo "# CI Bug Report (auto)" > docs/09_bug_report.md
          echo "Run: ${{ github.run_id }}" >> docs/09_bug_report.md
          echo "Date: $(date -u)" >> docs/09_bug_report.md
          echo "" >> docs/09_bug_report.md
          echo "## Failures" >> docs/09_bug_report.md
          echo "- TODO: Parse test outputs and list failures" >> docs/09_bug_report.md
      - name: Commit
        run: |
          git config user.name agent && git config user.email agent@users.noreply.github.com
          git add docs/09_bug_report.md
          git commit -m "chore: update bug report" || true
          git push || true
