name: 06 - Bug Report
on:
  workflow_run:
    workflows: ["05 - CI Tests"]
    types: [completed]
  workflow_dispatch: {}   # <-- cho phép chạy tay

permissions:
  contents: write         # <-- cho phép commit/push
  actions: read

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Summarize failures to docs/09_bug_report.md
        run: |
          echo "# CI Bug Report (auto)" > docs/09_bug_report.md
          echo "Run: ${{ github.run_id }}" >> docs/09_bug_report.md
          echo "Date: $(date -u)" >> docs/09_bug_report.md
          echo "" >> docs/09_bug_report.md
          echo "## Failures" >> docs/09_bug_report.md
          echo "- TODO: Parse test outputs and list failures" >> docs/09_bug_report.md

      # --- Nếu main không protected, dùng push trực tiếp:
      - name: Commit to main (if allowed)
        if: ${{ !contains(github.ref, 'refs/heads/') || github.ref == 'refs/heads/main' }}
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add docs/09_bug_report.md
          git commit -m "chore: update bug report [skip ci]" || echo "no changes"
          git push || echo "main protected, fallback to PR"

      # --- Fallback: tạo PR nếu branch được bảo vệ:
      - name: Create PR (fallback when push blocked)
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update bug report"
          title: "chore: update bug report"
          branch: "chore/bug-report-${{ github.run_id }}"
          delete-branch: true
          add-paths: |
            docs/09_bug_report.md
