name: 07 - Phase Gate
on:
  workflow_dispatch: {}
  schedule: [ { cron: "0 2 * * *" } ]
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate quality gates
        run: |
          echo "Check coverage, lighthouse, e2e from artifacts. If pass, increment phase in project.yaml"
      - name: Commit phase bump
        run: |
          git config user.name agent && git config user.email agent@users.noreply.github.com
          git add infra/context/project.yaml || true
          git commit -m "chore: phase++" || true
          git push || true
